#!/usr/bin/bash

# check if script ran with root privileges
if [ $EUID != 0 ]; then
  echo '[Error] This script requires root privileges'
  exit 1
fi

while getopts ":u" opts; do
	case $opts in
		u)
			target_user=$OPTARG
			;;
		*)
			echo "Something"
			;;
	esac
done

# default values
target_user=$SUDO_USER

# symlink_targets: target dir/files for the symbolic links.
# [target]=link
declare -A symlink_targets
symlink_targets["./bin"]="bin"
symlink_targets["./config"]=".config"
symlink_targets["./home/bashrc"]="~/.bashrc"

# req_packages: files in config require these packages to be installed
declare -a req_packages=("kakoune" "tmux")


# let's assume they're not doing this at the root user...
home_dir="/home/$target_user"

# Check if the configuration files exist
for target in ${!symlink_targets[@]}; do
	# Check the if the file exists
	if [[ ! -e "$target" ]]; then
		echo "$0: config file/dir not found: $target"
		exit 1
	fi
done

# Check if required packages are installed on the system
for package in ${req_packages[@]};do
	output=$(pacman -Q $package)
	if [[ $? -eq 1 ]];then
		echo "$0: $output"
		exit 1
	fi
done

# Check the if the home directory exists
if [[ ! -d $home_dir ]]; then
	echo "$0: $home_dir is not a directory "
	exit 1
fi

# create symlinks for config files in home directory
for target in ${!symlink_targets[@]};do
	echo "$home_dir/$symlink_targets[$target] <-- ./$target"
	ln -s  "$home_dir/$symlink_targets[$target]" "./$target"
done

echo "$0: script complete"
# SUDO_USER
# SUDO_UID
# SUDO_HOME


