#!/usr/bin/bash

# check if script ran with root privileges
if [ $EUID != 0 ]; then
  echo '$0: This script requires root privileges'
  exit 1
fi

usage () {
	echo "Usage: $0 [OPTIONS] FILE"
	echo "FILE is a list of packages to install separated by new lines or whitespace"
	echo "Options:"
	echo " -h						Display this help message"
	echo " -c						Show a confirmation prompt before installing packages"
}


# default options
confirm=false

while getopts ":c" opts; do
  case $opts in
    c) # show confirmation prompt before installing packages
      confirm=true
      ;;
		*|h|help)
      usage
			exit 1
      ;;
  esac
done

# shift options to get arguments
shift $(($OPTIND-1))
package_file=$1

if [[ -z $package_file ]];then
	usage
	exit 1
fi

# Check if script was passed a readable file
if [[ ! -f $package_file ]]; then
	echo "0: $package_file is not a file"
	exit 1
elif [[ ! -r $package_file ]];then
	echo "0: $package_file is not readable"
	exit 1
fi

# Parse packages from package_file
# Every line of the file is appended to a single variable
# New lines and white space act as delimiters between packages
cat $1 | while read p; do
	packages="$packages $p"
done


# Refresh package DB and upgrade existing pakabes
pacman -Syu --noconfirm

# Install selected packages
if [[ confirm = true ]]; then
  pacman -S $packages
else
  pacman -S --noconfirm $packages
fi

echo "$0: script completed"
