#!/usr/bin/bash

# setup-config
#		This script executes the scripts install-packages and/or create-symlinks.

# Variables behaviour
# The value of scripts determins which scripts are installed
# 1 = install-packages
# 2 = create-symlinks
# 3 = all
scripts=3
# package list for install-packages
package_file="packages"

# create-symlinks flags
cs_flags=""

usage () {
	echo "Usage: $0 [OPTIONS]"
	echo "Options:"
	echo " -h						Display this help message"
	echo " -p						Only install packages"
	echo " -s						Only create symbolic link"
	echo " -l						FILE Specify a list of packages to install"
	echo " -f						Force copying /etc/skel into new user's home directory"
}

# if the last program returns an exit code not equal to 0, set error to true
# Error will make the script echo that an error happened
check_exit_code () {
	if [[ $? -ne 0 ]];then
		error=true
	fi
}

while getopts ":pshl:f" opts;do
	case $opts in
		p)
			# run install-packages onlyi
			scripts=1
			;;
		s)
			# run create-symlinks only
			scripts=2
			;;
		l)
			# pass a file to use in install-packages
			if [[ -z $OPTARG ]];then
				usage
				exit
			fi
			package_file=$OPTARG
			;;
		f)
			# enable -f/force option for create-symlinks
			cs_flags="$cs_flags -f"
			;;
		*|h|help)
			usage
			exit 1
			;;
	esac
done

case $scripts in
	1)
		./install-packages $package_file
		;;
	2)
		./create-symlinks $cs_flags
		;;
	3)
		./install-packages $package_file
		./create-symlinks $cs_flags
		;;
esac

check_exit_code
if [[ $error = true ]];then
	echo "$0: error occured"
else
	echo "$0: script completed"
fi
